using AiSetup.Aggregation;
using AiSetup.Models;

namespace AiSetup.Tests.Aggregation;

public sealed class MarkdownAggregatorTests
{
    [Fact]
    public void Aggregate_OrdersInstructionsBeforeAgentsAndIncludesBanner()
    {
        var sut = new MarkdownAggregator();

        var output = sut.Aggregate(new[]
        {
            NewAsset(AssetType.Agent, "z-agent", "Agent body"),
            NewAsset(AssetType.Instruction, "csharp/csharp.instructions", "Instr body")
        });

        output.Should().StartWith("<!-- Generated by ai-setup");
        var instructionIndex = output.IndexOf("Instr body", StringComparison.Ordinal);
        var agentIndex = output.IndexOf("Agent body", StringComparison.Ordinal);
        instructionIndex.Should().BePositive();
        agentIndex.Should().BeGreaterThan(instructionIndex);
    }

    [Fact]
    public void Aggregate_FiltersOutSkillAndMcpAssets()
    {
        var sut = new MarkdownAggregator();

        var output = sut.Aggregate(new[]
        {
            NewAsset(AssetType.Skill, "csharp/dotnet-tester", "should not appear"),
            NewAsset(AssetType.McpConfig, "github", "also not"),
            NewAsset(AssetType.Instruction, "general/code", "should appear")
        });

        output.Should().Contain("should appear");
        output.Should().NotContain("should not appear");
        output.Should().NotContain("also not");
    }

    [Fact]
    public void Aggregate_RendersApplyToHint()
    {
        var sut = new MarkdownAggregator();

        var asset = new AssetDefinition(
            "x", AssetType.Instruction, "x", "desc", [], [],
            "/x", "**/*.cs", new Dictionary<string, object?>(), "body");

        var output = sut.Aggregate([asset]);

        output.Should().Contain("Applies to: `**/*.cs`");
    }

    private static AssetDefinition NewAsset(AssetType type, string id, string body) => new(
        Id: id,
        Type: type,
        Name: id,
        Description: string.Empty,
        Tags: [],
        Targets: [],
        SourcePath: "/" + id,
        ApplyTo: null,
        Frontmatter: new Dictionary<string, object?>(),
        Body: body);
}
