using System.Text;
using AiSetupLib.Models;

namespace AiSetupLib.Aggregation;

public sealed class MarkdownAggregator : IContentAggregator
{
    private static readonly AssetType[] TypeOrder =
    [
        AssetType.Instruction,
        AssetType.Skill,
        AssetType.Agent,
        AssetType.McpConfig,
    ];

    public string Aggregate(IReadOnlyList<AssetDefinition> assets)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# AI-Setup Aggregated Configuration");
        sb.AppendLine();
        sb.AppendLine("> Generated by ai-setup. Do not edit by hand.");
        sb.AppendLine();

        var ordered = assets
            .OrderBy(a => Array.IndexOf(TypeOrder, a.Type))
            .ThenBy(a => a.Name, StringComparer.Ordinal);

        foreach (var asset in ordered)
        {
            sb.Append("## ").Append(asset.Type).Append(": ").AppendLine(asset.Name);
            sb.AppendLine();
            if (!string.IsNullOrWhiteSpace(asset.Description))
            {
                sb.Append("> ").AppendLine(asset.Description);
                sb.AppendLine();
            }
            sb.AppendLine(asset.Body.TrimEnd());
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
