using System.Text;
using AiSetupLib.Models;

namespace AiSetupLib.Aggregation;

public sealed class MarkdownAggregator : IContentAggregator
{
    private static readonly AssetType[] TypeOrder =
    [
        AssetType.Instruction,
        AssetType.Skill,
        AssetType.Agent,
        AssetType.McpConfig,
    ];

    public string Aggregate(IReadOnlyList<AssetDefinition> assets)
    {
        var sb = new StringBuilder();
        sb.Append("# AI-Setup Aggregated Configuration\n");
        sb.Append('\n');
        sb.Append("> Generated by ai-setup. Do not edit by hand.\n");
        sb.Append('\n');

        var ordered = assets
            .OrderBy(a => Array.IndexOf(TypeOrder, a.Type))
            .ThenBy(a => a.Name, StringComparer.Ordinal);

        foreach (var asset in ordered)
        {
            sb.Append("## ").Append(Label(asset.Type)).Append(": ").Append(asset.Name).Append('\n');
            sb.Append('\n');
            if (!string.IsNullOrWhiteSpace(asset.Description))
            {
                sb.Append("> ").Append(asset.Description).Append('\n');
                sb.Append('\n');
            }
            sb.Append(asset.Body.TrimEnd()).Append('\n');
            sb.Append('\n');
        }

        return sb.ToString();
    }

    private static string Label(AssetType t) => t switch
    {
        AssetType.Instruction => "Instruction",
        AssetType.Skill => "Skill",
        AssetType.Agent => "Agent",
        AssetType.McpConfig => "McpConfig",
        _ => throw new ArgumentOutOfRangeException(nameof(t)),
    };
}
