using System.Text;
using AiSetup.Models;
using CreativeCoders.Core;

namespace AiSetup.Aggregation;

/// <summary>
/// Default <see cref="IMarkdownAggregator"/>. Emits sections in the order
/// instructions → agents and prepends a generated banner.
/// </summary>
public sealed class MarkdownAggregator : IMarkdownAggregator
{
    private const string Banner = "<!-- Generated by ai-setup. Do not edit by hand. -->";

    /// <inheritdoc />
    public string Aggregate(IReadOnlyList<AssetDefinition> assets)
    {
        Ensure.NotNull(assets);

        var ordered = assets
            .Where(a => a.Type is AssetType.Instruction or AssetType.Agent)
            .OrderBy(a => a.Type == AssetType.Instruction ? 0 : 1)
            .ThenBy(a => a.Id, StringComparer.Ordinal)
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine(Banner);
        builder.AppendLine();

        foreach (var asset in ordered)
        {
            AppendSection(builder, asset);
        }

        return builder.ToString();
    }

    private static void AppendSection(StringBuilder builder, AssetDefinition asset)
    {
        builder.Append("## ").AppendLine(asset.Name);

        if (!string.IsNullOrWhiteSpace(asset.Description))
        {
            builder.AppendLine();
            builder.AppendLine(asset.Description.Trim());
        }

        if (!string.IsNullOrWhiteSpace(asset.ApplyTo))
        {
            builder.AppendLine();
            builder.Append("> Applies to: `").Append(asset.ApplyTo).AppendLine("`");
        }

        builder.AppendLine();
        builder.AppendLine(asset.Body.TrimEnd());
        builder.AppendLine();
    }
}
